name = "mimotion-trigger"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[triggers]
crons = ["7 0,1,2,4,5,6,10,11,12 * * *"]

[vars]
GITHUB_OWNER = "ylroki"
GITHUB_REPO = "mimotion"

[observability]
enabled = true
